apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-notification-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-notification-api
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: user-notification-api
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
        - name: user-notification-api
          image: {{image}}
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: 256Mi
              cpu: 50m
            limits:
              memory: 768Mi
              cpu: 100m
      imagePullSecrets:
        - name: dockerhubcert
---
apiVersion: v1
kind: Service
metadata:
  name: user-notification-api-service
spec:
  type: ClusterIP
  ports:
    - port: 80
  selector:
    app: user-notification-api
